esphome:
  name: acz.dht11
  friendly_name: Remote Temperature/Humidity Sensor
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome

wifi:
  # Set up a wifi access point using the device name above
  ap:

sensor:
  - platform: dht
    model: DHT11
    pin: GPIO11
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:
